import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// --- Release signing ------------------------------------------------------
//
// The keystore lives outside the repository and is pointed at by
// android/key.properties, which is generated by
// android/tool/new_release_keystore.ps1 and is git-ignored. Neither the key nor
// its password is ever in a commit.
//
// On a machine without key.properties, debug builds still work; release builds
// stop dead. That is deliberate - see the check below.
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
val hasReleaseSigning = keystorePropertiesFile.exists()
if (hasReleaseSigning) {
    keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
}

// A release APK signed with the debug key is worse than no APK at all: the
// debug key is a well-known, shared, publicly available key, so anyone can
// forge an "update" that Android will install straight over the top of the
// real app. The old template here silently did exactly that. Rather than fall
// back to it, a release build without a keystore fails, and says why.
val wantsRelease = gradle.startParameter.taskNames.any {
    it.contains("release", ignoreCase = true)
}
if (wantsRelease && !hasReleaseSigning) {
    throw GradleException(
        """
        |
        |No release keystore configured.
        |
        |  Expected: ${keystorePropertiesFile.absolutePath}
        |
        |Create one with:
        |  powershell -ExecutionPolicy Bypass -File android\tool\new_release_keystore.ps1
        |
        |If you already have the keystore, restore android/key.properties with
        |storeFile / storePassword / keyAlias / keyPassword pointing at it.
        |
        |This build will not fall back to the debug signing key: the debug key is
        |public, so anything signed with it can be replaced by anyone.
        """.trimMargin()
    )
}

android {
    namespace = "com.rahozosman.hozasend"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        // flutter_local_notifications uses java.time on all API levels, which
        // only exists natively from API 26. Desugaring back-ports it, so the
        // app can still run on older phones.
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // Permanent. Android identifies an app by this string plus its signing
        // key; changing either one makes it a different app that cannot be
        // installed over the existing one. Matches the Microsoft Store identity
        // (rahozosman.hozasend) so the publisher is the same across platforms.
        applicationId = "com.rahozosman.hozasend"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        // Both come from `version:` in pubspec.yaml - 1.0.0+1 gives
        // versionName 1.0.0 and versionCode 1. Bump the +N on every release you
        // publish: Android refuses to install an APK whose versionCode is not
        // greater than the installed one.
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        // The desugared library plus the plugin set pushes past the 64k method
        // limit on older API levels.
        multiDexEnabled = true
    }

    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = keystoreProperties.getProperty("storeFile")?.let { file(it) }
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")

                // Sign with every scheme the platform understands. v1 is what
                // Android 6 and below verify, v2 arrived in Android 7 and v3 in
                // Android 9; a sideloaded APK meets all of them in the wild, and
                // v2/v3 are also what make the APK tamper-evident as a whole
                // file rather than entry by entry.
                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
                // v4 is only useful for `adb install --incremental`, and it
                // emits a separate .apk.idsig file that would just be an extra
                // confusing download on a Releases page.
                enableV4Signing = false
            }
        }
    }

    buildTypes {
        release {
            signingConfig = if (hasReleaseSigning) {
                signingConfigs.getByName("release")
            } else {
                // Unreachable: the guard above has already failed the build.
                // Left explicit so nothing can silently inherit debug signing.
                null
            }

            // R8 shrinks and optimises the Java/Kotlin half of the app and
            // strips the resources nothing references. The Dart half is already
            // AOT-compiled into libapp.so and is untouched by this.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )

            // Explicit rather than inherited, so a stray `debuggable true`
            // cannot arrive from a plugin's manifest merge unnoticed.
            isDebuggable = false
            isJniDebuggable = false
        }
    }
}

dependencies {
    // Required by the compileOptions flag above. Must be 2.1.x or newer for
    // the AGP version Flutter 3.44 ships with.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")

    // FileProvider, for handing a received file to the app that opens its
    // kind. Declared rather than inherited from a plugin: the host code
    // compiles against it, and a transitive dependency can be dropped by
    // whichever plugin happened to be bringing it in.
    implementation("androidx.core:core:1.13.1")
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
