name: Flutter Release

on:
  workflow_dispatch:

jobs:

  android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab


  windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/


  macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --release

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/


  ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign